# Generated by Django 2.2 on 2021-10-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tumblr',
            fields=[
                ('tumblr_id_str', models.CharField(default='tumblr_id_str', max_length=100, primary_key=True, serialize=False)),
                ('tumblr_type_str', models.CharField(default='tumblr_type_str', max_length=100)),
                ('blogname_str', models.CharField(default='tumblr_blogname_str', max_length=100)),
                ('blog_name_str', models.CharField(default='tumblr_blog_name_str', max_length=100)),
                ('blog_title_str', models.CharField(default='tumblr_blog_title_str', max_length=100)),
                ('blog_description_str', models.CharField(default='tumblr_blog_description_str', max_length=100)),
                ('blog_url_str', models.CharField(default='tumblr_blog_url_str', max_length=100)),
                ('blog_uuid_str', models.CharField(default='tumblr_blog_uuid_str', max_length=100)),
                ('updated_at', models.IntegerField(default=0)),
                ('post_url_str', models.CharField(default='tumblr_post_url_str', max_length=100)),
                ('date', models.CharField(default='date', max_length=100)),
                ('timestamp', models.IntegerField(default=0)),
                ('state', models.CharField(default='state', max_length=100)),
                ('format', models.CharField(default='format', max_length=100)),
                ('comment', models.TextField(default='comment', max_length=100)),
                ('can_reblog', models.BooleanField(default=False)),
                ('can_reply', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_id_str', models.CharField(default='tweet_id_str', max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.CharField(default='created_at', max_length=100)),
                ('text', models.TextField(default='TextField', max_length=280)),
                ('device', models.CharField(default='device', max_length=100)),
                ('truncated', models.BooleanField(default=False)),
                ('retweet_count', models.IntegerField(default=0)),
                ('lang', models.CharField(default='language', max_length=100)),
                ('country', models.CharField(default='usa', max_length=200)),
                ('in_reply_to_status_id_str', models.CharField(default='in_reply_to_status_id_str', max_length=100, null=True)),
                ('in_reply_to_user_id_str', models.CharField(default='in_reply_to_user_id_str', max_length=100, null=True)),
                ('in_reply_to_screen_name', models.CharField(default='in_reply_to_screen_name', max_length=100, null=True)),
                ('hashtags', models.CharField(default=[''], max_length=200, null=True)),
                ('sentiment', models.CharField(default=[''], max_length=10, null=True)),
                ('user_id_str', models.CharField(default='user_id_str', max_length=100)),
                ('name', models.CharField(default='name', max_length=100)),
                ('screen_name', models.CharField(default='screen_name', max_length=100)),
                ('url', models.CharField(default='urls', max_length=100, null=True)),
                ('description', models.CharField(default='description', max_length=300)),
                ('verified', models.BooleanField(default=False)),
                ('followers_count', models.IntegerField(default=0)),
                ('friends_count', models.IntegerField(default=0)),
                ('listed_count', models.IntegerField(default=0)),
                ('favourites_count', models.IntegerField(default=0)),
                ('num_tweets', models.IntegerField(default=0)),
                ('user_created_at', models.DateTimeField(null=True)),
                ('utc_offset', models.CharField(default='utc_offset', max_length=100, null=True)),
                ('time_zone', models.DateTimeField(null=True)),
                ('geo_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
