# Generated by Django 2.2 on 2021-10-21 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('consumer_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('access_token', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('access_token_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('social_platform', models.TextField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
