# Generated by Django 2.2 on 2021-10-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tumblr_Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60, verbose_name='user')),
                ('tumblr_study_id', models.CharField(max_length=100, verbose_name='tumblr_study_id')),
                ('count', models.BigIntegerField(verbose_name='count')),
                ('posts', models.ManyToManyField(to='query.Tumblr')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60, verbose_name='user')),
                ('study_id', models.CharField(max_length=100, verbose_name='study_id')),
                ('count', models.BigIntegerField(verbose_name='count')),
                ('tweets', models.ManyToManyField(to='query.Tweet')),
            ],
        ),
    ]
